package customfit.ai.kotlinclient

import org.joda.time.DateTime

data class SdkSettings(
        val cf_key: String,
        val cf_account_enabled: Boolean,
        val cf_skip_sdk: Boolean,
        val cf_page_elements_path_type: String?,
        val cf_latest_sdk_version: String?,
        val cf_whitelabel_company_display_name: String?,
        val cf_domain_url: String?,
        val cf_jsevl_type: String?,
        val cf_config_reapply_timers: String?,
        val cf_ga4_setup_mode: String?,
        val cf_gtm_data_variable_name: String?,
        val cf_account_source: String?,
        val cf_event_merge_config: String?,
        val cf_dimension_id: String?,
        val cf_intelligent_code_enabled: Boolean,
        val cf_personalize_post_sdk_timeout: Boolean,
        val is_inbound: Boolean,
        val is_outbound: Boolean,
        val cfspa: Boolean,
        val cfspa_auto_detect_page_url_change: Boolean,
        val is_auto_form_capture: Boolean,
        val is_auto_email_capture: Boolean,
        val cf_is_page_update_enabled: Boolean,
        val cf_retain_text_value: Boolean,
        val cf_is_whitelabel_account: Boolean,
        val enable_event_analyzer: Boolean,
        val cf_skip_dfs: Boolean,
        val cf_is_ms_clarity_enabled: Boolean,
        val cf_is_hotjar_enabled: Boolean,
        val cf_is_shopify_integrated: Boolean,
        val cf_is_ga_enabled: Boolean,
        val cf_is_segment_enabled: Boolean,
        val cf_is_mixpanel_enabled: Boolean,
        val cf_is_moengage_enabled: Boolean,
        val cf_is_clevertap_enabled: Boolean,
        val cf_is_webengage_enabled: Boolean,
        val cf_is_netcore_enabled: Boolean,
        val cf_is_amplitude_enabled: Boolean,
        val cf_is_heap_enabled: Boolean,
        val cf_is_gokwik_enabled: Boolean,
        val cf_is_shopflo_enabled: Boolean,
        val cf_send_error_report: Boolean,
        val personalized_users_limit_exceeded: Boolean,
        val cf_sdk_timeout_in_seconds: Int,
        val cf_initial_delay_in_ms: Int,
        val cf_last_visited_product_url: Int,
        val blacklisted_page_paths: List<String>?,
        val blacklisted_referrers: List<String>?,
        val cf_subdomains: List<String>?,
        val cf_configs_json: Map<String, Any>?,
        val cf_active_pages: Map<String, Any>?,
        val cf_revenue_pages: Map<String, Any>?,
        val cf_browser_variables: Map<String, Any>?,
        val date: DateTime?
)
