include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add additional lint rules here
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_this

analyzer:
  errors:
    # Ignore specific errors
    unused_field: ignore
